server:
  port: 8081
spring:
  application:
    name: user-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: public
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true
      - nacos:jackson.yaml?group=DEFAULT_GROUP&refresh-enabled=true
  datasource:
    url: jdbc:mysql://localhost:3307/yuanlive_user?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yuanlive
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.126.com # 自行选择126、qq或其他邮箱
    port: 465
    username: ${YUANLIVE_MAIL_USER}
    password: ${YUANLIVE_MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          # 关键点 1：必须开启 SSL，否则 465 端口会报 EOF
          ssl:
            enable: true
            trust: "*"
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: blog.yuanyuan.yuanlive.entity.user.entity
  global-config:
    db-config:
      id-type: auto

redis-key:
  register:
    prefix: "yuanlive:user:register:"
    ttl: 180
    timeunit: SECONDS
  forget:
    prefix: "yuanlive:user:forget:"
    ttl: 180
    timeunit: SECONDS
  refresh-token:
    prefix: "yuanlive:user:refreshtoken:"
    ttl: 7
    timeunit: DAYS
  qr-code:
    prefix: "yuanlive:user:qrcode:"
    ttl: 120
    timeunit: SECONDS
  user2refresh-token:
    prefix: "yuanlive:user:user2refresh-token:"
    ttl: ${redis-key.refresh-token.ttl}
    timeunit: ${redis-key.refresh-token.timeunit}
  login-limit:
    threshold: 3 # 登录失败次数阈值
    lock:
      prefix: "yuanlive:user:login:limit:"
      ttl: 180 # 登陆失败锁定时间
      timeunit: SECONDS
    fail-count:
      prefix: "yuanlive:user:login:failcount:"
      ttl: 10 # 登录失败次数缓存时间
      timeunit: SECONDS
  anchor-map: # 存储在线主播与房间id的映射 anchor_id -> room_id
    key: "yuanlive:live:anchor_map"

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  generator:
    enabled: true
  snowflake:
    enabled: true
    share:
      clock-sync: true
    zone-id: Asia/Shanghai
    provider:
      safe-js:
        machine-bit: 4
        sequence-bit: 8
    epoch: 1577203200000
  segment:
    enabled: true
    distributor:
      type: redis
    provider:
      user-follow:
        step: 5000
        offset: 1000
