server:
  port: 8084
spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: ${NVIDIA_API_KEY}
      base-url: https://integrate.api.nvidia.com # 注意此处路径不能带/v1
      chat:
        options:
          model: qwen/qwen3-next-80b-a3b-instruct # 模型可以自行选择

    max-messages: 5 # LLM模型获得的最大历史对话轮数

    mcp:
      client:
        enabled: true
        name: ai-service-mcp-client
        type: async
        version: 1.0.0
        request-timeout: 30s
# 在 spring.ai中配置
        sse:
          connections:
            # 取名时最好不要携带'-',避免过滤client出错
            liveMcp:
#              # 直接连接mcp server
#              url: http://localhost:8082
#              # higress 网关
              url: http://localhost:8075/gateway
              # nacos mcp router
#              url: http://127.0.0.1:8001
              sse-endpoint: /sse
#        # 测试 stdio mcp server
#        stdio:
#          servers-configuration: classpath:amap.json
        stdio:
          connections:
            amap:
              command: ${NODE_EXECUTABLE}
              args:
                - "${NODE_MODULES_ROOT}/@amap/amap-maps-mcp-server/build/index.js"
              env:
                AMAP_MAPS_API_KEY: ${AMAP_API_KEY}
            es:
              command: ${NODE_EXECUTABLE}
              args:
                - "${NODE_MODULES_ROOT}/@octodet/elasticsearch-mcp/build/index.js"
              env:
                - "ES_URL": "http://localhost:9200"
                - "ES_VERSION": "8"
            searxng:
              command: ${NODE_EXECUTABLE}
              args:
                - ${SEARXNG_PATH}
              env:
                "SEARXNG_URL": "http://localhost:8060"
            calculator:
              command: ${UVX_EXECUTABLE}
              args:
                - "mcp-server-calculator"

    alibaba:
      mcp:
        nacos:
          namespace: public
          server-addr: ${spring.cloud.nacos.server-addr}
          username: nacos
          password: nacos
          # 报错不影响(可以负载均衡，但是通过nacos-mcp-router中转无法负载均衡)
          # 只有使用nacos中的mcp server 才能负载均衡
          # 可以使用spring.ai接受stdio的mcp; spring.ai.alibaba.mcp.nacos接受sse或streamable的mcp
          client:
            enabled: true
            sse:
              connections:
                live-service-mcp-server:
                  service-name: live-service-mcp-server
                  version: 1.0.0
#                nacos-mcp-router:
#                  service-name: nacos-mcp-router
#                  version: 1.0.0
            configs:
              live-service-mcp-server: # 与 sse.connections中的内容一致
                namespace: public
                server-addr: ${spring.cloud.nacos.server-addr}
                username: nacos
                password: nacos

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        metadata:
          netty-port: ${yuanlive.netty.port}
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        namespace: public
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true
      - nacos:rabbitmq.yaml?group=DEFAULT_GROUP&refresh-enabled=true
      - nacos:jackson.yaml?group=DEFAULT_GROUP&refresh-enabled=true
#      - nacos:minio.yaml?group=DEFAULT_GROUP&refresh-enabled=true

  datasource:
    url: jdbc:mysql://localhost:3307/yuanlive_live?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yuanlive
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/yuanlive?replicaSet=rs0&serverSelectionTimeoutMS=5000

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: blog.yuanyuan.yuanlive.entity.live.entity
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.ai.openai: DEBUG
    blog.yuanyuan.yuanlive: DEBUG

risk:
  low: 20
  medium: 50
  high: 80

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  snowflake:
    enabled: true
    share:
      clock-sync: true
    zone-id: Asia/Shanghai
    provider:
      ai-chat-msg:
        machine-bit: 4
        sequence-bit: 8
    epoch: 1577203200000