server:
  port: 8084
spring:
  application:
    name: ai-service
  ai:
    openai:
      api-key: ${NVIDIA_API_KEY}
      base-url: https://integrate.api.nvidia.com # 注意此处路径不能带/v1
      chat:
        options:
          model: qwen/qwen3-next-80b-a3b-instruct # 模型可以自行选择
    mcp:
      client:
        enabled: true
        name: ai-service-mcp-client
        type: async
        version: 1.0.0
        request-timeout: 200s
# 在 spring.ai中配置(无法负载均衡)
#        sse:
#          connections:
#            server1:
#              # 直接连接mcp server
#              url: http://localhost:8082
#              # higress 网关
#              url: http://127.0.0.1:8075/mcp/live-service-mcp-server
              # nacos mcp router
#              url: http://127.0.0.1:8001
#              sse-endpoint: /sse
#        # 测试 stdio mcp server
#        stdio:
#          servers-configuration: classpath:amap.json
        stdio:
          connections:
            amap:
              command: "/home/frodepu/.nvm/versions/node/v22.13.1/bin/node" # 直接用 node 解释器
              args:
                - "/home/frodepu/.nvm/versions/node/v22.13.1/lib/node_modules/@amap/amap-maps-mcp-server/build/index.js" # 这里填入你查到的绝对路径
              env:
                AMAP_MAPS_API_KEY: "43f7df3386694e8037c923f40f3085e5"

    alibaba:
      mcp:
        nacos:
          namespace: public
          server-addr: ${spring.cloud.nacos.server-addr}
          username: nacos
          password: nacos
          # 报错不影响(可以负载均衡，但是通过nacos-mcp-router中转无法负载均衡)
          # 只有使用nacos中的mcp server 才能负载均衡
          # 可以使用spring.ai接受stdio的mcp; spring.ai.alibaba.mcp.nacos接受sse或streamable的mcp
          client:
            enabled: true
            sse:
              connections:
                live-service-mcp-server:
                  service-name: live-service-mcp-server
                  version: 1.0.0
#                nacos-mcp-router:
#                  service-name: nacos-mcp-router
#                  version: 1.0.0
            configs:
              live-service-mcp-server: # 与 sse.connections中的内容一致
                namespace: public
                server-addr: ${spring.cloud.nacos.server-addr}
                username: nacos
                password: nacos


  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        metadata:
          netty-port: ${yuanlive.netty.port}
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        namespace: public
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true
      - nacos:rabbitmq.yaml?group=DEFAULT_GROUP&refresh-enabled=true
#      - nacos:jackson.yaml?group=DEFAULT_GROUP&refresh-enabled=true
#      - nacos:minio.yaml?group=DEFAULT_GROUP&refresh-enabled=true

  datasource:
    url: jdbc:mysql://localhost:3307/yuanlive_live?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yuanlive
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: blog.yuanyuan.yuanlive.entity.live.entity
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.ai.openai: DEBUG
    blog.yuanyuan.yuanlive: DEBUG

risk:
  low: 20
  medium: 50
  high: 80