server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: public
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]': # 拦截所有请求
                allowedOriginPatterns: "*"  # 允许所有来源 (支持带 Cookie)
                allowedMethods: # 允许的 HTTP 方法
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"         # 允许所有请求头 (Authorization, Content-Type, traceId 等)
                allowCredentials: true      # 允许携带 Cookie/凭证
                maxAge: 3600                # 跨域检测有效期 (秒)
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
            - id: live-service
              uri: lb://live-service
              predicates:
                - Path=/live/**
              filters:
                - StripPrefix=1
            - id: websocket-route
              uri: lb:ws://live-service
              predicates:
                - Path=/ws/**
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true


knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    strategy: discover
    discover:
      excluded-services:
        - seata-server
        - gateway-service

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG