server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: public
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user/**
              filters:
                - StripPrefix=1
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true


knife4j:
  gateway:
    enabled: true
    tags-sorter: order
    operations-sorter: order
    strategy: discover
    discover:
      excluded-services:
        - seata-server
        - gateway-service