version: '3.8'

services:
  # 流媒体服务器 SRS
  srs:
    image: ossrs/srs:v6.0.184
    container_name: yuanlive-srs
    ports:
      - "1935:1935"
      - "1985:1985"
      - "18080:8080"
    #      - "8000:8000/udp"
    #      - "10080:10080/udp"
    volumes:
      - ./SrsConfig/srs.conf:/usr/local/srs/conf/docker.conf
      - ./SrsConfig/logs:/usr/local/srs/objs/logs
      - ./SrsConfig/nginx/html:/usr/local/srs/objs/nginx/html
    command: ./objs/srs -c conf/docker.conf
    networks:
      - live-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  # 数据库
  mysql:
    image: mysql:8.0.44-debian
    container_name: yuanlive-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yuanlive
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - live-net
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -pyuanlive -e 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: unless-stopped
  # nacos注册中心
  nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: yuanlive-nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN=YXNqaGRndXF3eWdqaHNhZmlxYWhka2p5aWpkZXdqZGlhcw==
      - NACOS_AUTH_IDENTITY_KEY=yuanlive
      - NACOS_AUTH_IDENTITY_VALUE=yuanlive
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=yuanlive
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8034:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/data:/home/nacos/data
    networks:
      - live-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  # 分布式事务
  seata:
    image: apache/seata-server:2.5.0
    container_name: yuanlive-seata
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_IP=seata
      - SEATA_PORT=8091
      - SEATA_STORE_MODE=db
      - SEATA_STORE_DB_DATASOURCE=druid
      - SEATA_STORE_DB_DB_TYPE=mysql
      - SEATA_STORE_DB_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SEATA_STORE_DB_URL=jdbc:mysql://mysql:3306/seata?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
      - SEATA_STORE_DB_USER=root
      - SEATA_STORE_DB_PASSWORD=yuanlive

      - SEATA_REGISTRY_TYPE=nacos
      - SEATA_REGISTRY_NACOS_SERVER_ADDR=nacos:8848
      - SEATA_REGISTRY_NACOS_GROUP=SEATA_GROUP
      - SEATA_REGISTRY_NACOS_USERNAME=nacos
      - SEATA_REGISTRY_NACOS_PASSWORD=nacos
    volumes:
      - ./seata/lib/mysql-connector-j-8.2.0.jar:/seata-server/libs/mysql-connector-j-8.2.0.jar
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - live-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  # redis
  redis:
    image: redis:8.4.0
    container_name: yuanlive-redis
    ports:
      - "6378:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - live-net
    restart: unless-stopped

networks:
  live-net:
    driver: bridge
    name: live-net