version: '3.8'

services:
  # 流媒体服务器 SRS
  srs:
    image: ossrs/srs:v6.0.184
    container_name: yuanlive-srs

    ports:
      - "1935:1935"
      - "1985:1985"
      - "18080:8080"
      - "8000:8000/udp"
    #      - "10080:10080/udp"
    environment:
      - CANDIDATE=${HOST_IP}

    volumes:
      - ./SrsConfig/srs.conf:/usr/local/srs/conf/docker.conf
      - ./SrsConfig/logs:/usr/local/srs/objs/logs
      - ./SrsConfig/nginx/html:/usr/local/srs/objs/nginx/html
    command: >
      sh -c "umask 000 && exec ./objs/srs -c conf/docker.conf"
    networks:
      - live-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  # 数据库
  mysql:
    image: mysql:8.0.44-debian
    container_name: yuanlive-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yuanlive
      TZ: Asia/Shanghai
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - live-net
    healthcheck:
      test: [ "CMD-SHELL", "mysql -u root -pyuanlive -e 'SELECT 1'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    restart: unless-stopped
  # nacos注册中心
  nacos:
    image: nacos/nacos-server:v3.1.0
    container_name: yuanlive-nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_TOKEN=YXNqaGRndXF3eWdqaHNhZmlxYWhka2p5aWpkZXdqZGlhcw==
      - NACOS_AUTH_IDENTITY_KEY=yuanlive
      - NACOS_AUTH_IDENTITY_VALUE=yuanlive
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=yuanlive
    ports:
      - "8848:8848"
      - "9848:9848"
      - "8034:8080"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./nacos/logs:/home/nacos/logs
      - ./nacos/data:/home/nacos/data
    networks:
      - live-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  # Nacos MCP Router：中心化 AI 工具网关
  nacos-mcp-router:
    image: nacos/nacos-mcp-router:0.2.2
    container_name: yuanlive-nacos-mcp-router
    depends_on:
      - nacos
    environment:
      - NACOS_ADDR=nacos:8848
      - NACOS_USERNAME=nacos
      - NACOS_PASSWORD=nacos
      - TRANSPORT_TYPE=sse
      - MODE=router
    ports:
      - "8001:8000"
    networks:
      - live-net
  # 分布式事务
  seata:
    image: apache/seata-server:2.3.0
    container_name: yuanlive-seata
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_IP=seata
      - SEATA_PORT=8091

      - SEATA_REGISTRY_TYPE=nacos
      - SEATA_REGISTRY_NACOS_SERVER_ADDR=nacos:8848
      - SEATA_REGISTRY_NACOS_GROUP=SEATA_GROUP
      - SEATA_REGISTRY_NACOS_USERNAME=nacos
      - SEATA_REGISTRY_NACOS_PASSWORD=nacos

      - SEATA_CONFIG_TYPE=nacos
      - SEATA_CONFIG_NACOS_SERVER_ADDR=nacos:8848
      - SEATA_CONFIG_NACOS_GROUP=SEATA_GROUP
      - SEATA_CONFIG_NACOS_USERNAME=nacos
      - SEATA_CONFIG_NACOS_PASSWORD=nacos
      - SEATA_CONFIG_NACOS_DATA_ID=seata-server.properties
    volumes:
      - ./seata/lib/mysql-connector-j-8.2.0.jar:/seata-server/libs/mysql-connector-j-8.2.0.jar
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_started
    networks:
      - live-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  # sentinel 熔断
  sentinel:
    image: bladex/sentinel-dashboard:1.8.9
    container_name: yuanlive-sentinel
    environment:
      - SENTINEL_DASHBOARD_AUTH_USERNAME=sentinel
      - SENTINEL_DASHBOARD_AUTH_PASSWORD=sentinel
    ports:
      - "8858:8858"
    networks:
      - live-net
    restart: unless-stopped
  # redis
  redis:
    image: redis:8.4.0
    container_name: yuanlive-redis
    ports:
      - "6378:6379"
    volumes:
      - ./redis/data:/data
    networks:
      - live-net
    restart: unless-stopped
  # minio
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: yuanlive-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data:/data
    environment:
      MINIO_ROOT_USER: yuanlive
      MINIO_ROOT_PASSWORD: yuanlive
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      - live-net
  # rabbitmq
  mq:
    image: rabbitmq:4-management
    container_name: yuanlive-mq
    hostname: mq
    restart: unless-stopped
    ports:
      - "15672:15672"  # 管理界面端口
      - "5672:5672"    # AMQP 通讯端口
    environment:
      RABBITMQ_DEFAULT_USER: yuanlive
      RABBITMQ_DEFAULT_PASS: yuanlive
    volumes:
      - ./rabbitmq/mq-plugins/rabbitmq_delayed_message_exchange-4.2.0.ez:/opt/rabbitmq/plugins/rabbitmq_delayed_message_exchange-4.2.0.ez
      - ./rabbitmq/mq-data:/var/lib/rabbitmq
    networks:
      - live-net

  # elasticsearch
  es:
    image: elasticsearch:9.2.4
    container_name: yuanlive-es
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
    networks:
      - live-net
  # kibana
  kibana:
    image: elastic/kibana:9.2.4
    container_name: yuanlive-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://es:9200
    depends_on:
      - es
    networks:
      - live-net
  # logstash
  logstash:
    image: elastic/logstash:9.2.4
    container_name: yuanlive-logstash
    restart: unless-stopped
    ports:
      - "5044:5044"
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - es
    networks:
      - live-net
  # 4. Filebeat (日志搬运工)
  filebeat:
    image: elastic/filebeat:9.2.4
    container_name: yuanlive-filebeat
    restart: unless-stopped
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../logs:/var/log/yuanlive-logs
    command: ["-e", "--strict.perms=false", "-d", "*"]
    depends_on:
      - logstash
    networks:
      - live-net

networks:
  live-net:
    driver: bridge
    name: live-net