input {
  beats {
    port => 5044
  }
}

filter {
  # 对应你的 Logback 格式:
  # %d{...} ${LOG_LEVEL...} [%X{traceId}] --- [%thread] %logger : %msg
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_time}\s+%{LOGLEVEL:level}\s+\[%{DATA:traceId}\]\s+---\s+\[%{DATA:thread}\]\s+%{DATA:logger}\s+:\s+%{GREEDYDATA:msg}"
    }
  }
}

output {
  elasticsearch {
    hosts => ["es:9200"]
    index => "yuanlive-%{[service_name]}-%{+YYYY.MM.dd}"
  }
  # 调试用：打印到 Logstash 控制台
  stdout { codec => rubydebug }
}