input {
  beats {
    port => 5044
  }
}

filter {
  # 对应你的 Logback 格式:
  # %d{...} ${LOG_LEVEL...} [%X{traceId}] --- [%thread] %logger : %msg
  grok {
    match => {
      "message" => "%{TIMESTAMP_ISO8601:log_time}\s+%{LOGLEVEL:level}\s+\[%{DATA:traceId}\]\s+---\s+\[%{DATA:thread}\]\s+%{DATA:logger}\s+:\s+%{GREEDYDATA:msg}"
    }
  }
  date {
      # 匹配你的日志时间格式，根据你的Grok pattern看起来是 ISO8601
      match => ["log_time", "ISO8601", "yyyy-MM-dd HH:mm:ss.SSS"]
      target => "@timestamp"
      timezone => "Asia/Shanghai"
    }
  mutate {
      remove_field => [
        "agent",
        "ecs",
        "input",
        "log",
        "tags",
        "@version",
        "log_time"
      ]
    }
}

output {
  elasticsearch {
    hosts => ["es:9200"]
    index => "yuanlive-logs-%{[service_name]}-%{+YYYY.MM.dd}"
  }
  # 调试用：打印到 Logstash 控制台
  stdout { codec => rubydebug }
}