# 监听端口
listen              1935;
max_connections     1000;
daemon              off;

rtc_server {
    enabled         on;
    listen          8000; # UDP端口
    # 使用环境变量中的 IP 作为候选 IP
    candidate       $CANDIDATE;
}

# 开启 HTTP API (用于监控)
http_api {
    enabled         on;
    listen          1985;
}

# 开启 HTTP Server (用于分发 FLV 和 HLS 流)
http_server {
    enabled         on;
    listen          8080;
    dir             ./objs/nginx/html;
}

vhost __defaultVhost__ {
    # 最小延迟配置
    tcp_nodelay     on;
    min_latency     on;

    # 开启 HTTP-FLV 播放支持
    http_remux {
        enabled     on;
        mount       [vhost]/[app]/[stream].flv;
    }

    # 开启 DVR (录流回放)
    dvr {
            enabled             on;
            dvr_path            ./objs/nginx/html/forward/[app]/[stream]/[timestamp].mp4;
            dvr_plan            session; # 每个直播会话录制成一个文件
    }

    # 开启 HLS 播放支持 (m3u8, 兼容iOS)
    hls {
        enabled     on;
    }

    # --- 关键：后续对接 SpringCloud 的地方 ---
    http_hooks {
        enabled         on;
        # 推流时回调（鉴权）
        on_publish      http://host.docker.internal:8080/live/room/start;
        # 关播时回调
        on_unpublish    http://host.docker.internal:8080/live/room/end;
        # 存放录像文件时回调
        on_dvr          http://host.docker.internal:8080/live/room/dvr;
    }

    rtc {
            enabled     on;
            # 开启 RTMP 转 RTC (用于 WebRTC 播放，可选)
            rtmp_to_rtc on;
            # 【关键】开启 RTC 转 RTMP
            # 作用：你用 WebRTC 推流，SRS 自动把它转成 RTMP/FLV，
            # 这样普通观众依然可以通过 http-flv 观看。
            rtc_to_rtmp on;
        }
}