server:
  port: 8082
spring:
  application:
    name: live-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        metadata:
          netty-port: ${yuanlive.netty.port}
        server-addr: ${spring.cloud.nacos.server-addr}
      config:
        namespace: public
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true
      - nacos:jackson.yaml?group=DEFAULT_GROUP&refresh-enabled=true
      - nacos:minio.yaml?group=DEFAULT_GROUP&refresh-enabled=true

  datasource:
    url: jdbc:mysql://localhost:3307/yuanlive_live?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yuanlive
    driver-class-name: com.mysql.cj.jdbc.Driver

  rabbitmq:
    host: localhost   # 你的 Docker MQ 地址
    port: 5672
    username: yuanlive
    password: yuanlive
    # 关键：开启消息确认机制 (可选)
    publisher-confirm-type: correlated
    publisher-returns: true


mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: blog.yuanyuan.yuanlive.entity.live.entity
  global-config:
    db-config:
      id-type: auto

yuanlive:
  chat:
    mq:
      exchange: live.chat.fanout
    heartbeat: 30 # 心跳间隔 单位秒
  netty:
    port: 18081
    path: /ws
file-prefix:
  host-prefix: "/home/frodepu/IdeaProjects/yuanlive-cloud/docker/SrsConfig"
redis-key:
  active-rooms:
    key: "yuanlive:live:active_rooms"
  room2client:
    prefix: "yuanlive:live:room2client:"
  anchor-map: # 存储在线主播与房间id的映射 anchor_id -> room_id
    key: "yuanlive:live:anchor_map"
  live-room: # 直播间相关信息
    session-prefix: "yuanlive:live:session:" # 直播间会话信息(最高人数、房间clientId、recordId)
    current-prefix: "yuanlive:live:current:" # 直播间当前观众id集合
    total-prefix: "yuanlive:live:total:" # 直播间累计人数，使用hyperloglog



cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  snowflake:
    enabled: true
    share:
      clock-sync: true
    zone-id: Asia/Shanghai
    provider:
      safe-js:
        machine-bit: 4
        sequence-bit: 8
    epoch: 1577203200000
  segment:
    enabled: true
    distributor:
      type: redis
    provider:
      live-record:
        step: 5000
        offset: 1000