server:
  port: 8083

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    config:
      namespace: public
  application:
    name: wallet-service
  config:
    import:
      - nacos:sa-token.yaml?group=SA_TOKEN_GROUP&refresh-enabled=true
      - nacos:redis.yaml?group=REDIS_GROUP&refresh-enabled=true
      - nacos:rabbitmq.yaml?group=DEFAULT_GROUP&refresh-enabled=true
  datasource:
    url: jdbc:mysql://localhost:3307/yuanlive_user?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yuanlive
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: blog.yuanyuan.yuanlive.entity.wallet.entity
  global-config:
    db-config:
      id-type: auto

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: redis
  generator:
    enabled: true
  snowflake:
    enabled: true
    share:
      clock-sync: true
    zone-id: Asia/Shanghai
    provider:
      safe-js:
        machine-bit: 4
        sequence-bit: 8
    epoch: 1577203200000